### ISSUE TITLE
temp key is not created for many-to-many table

### ISSUE THREAD

**Issue by redwards510** [MapsterMapper/Mapster#128]
i filed this one with the EFCore team, but they are putting it back on Mapster. Here's my setup:
```csharp
TypeAdapterConfig<ServiceAreaDTO, ServiceArea>
    .NewConfig()
    .Map(dest => dest.ServiceAreaToZipCodes,
            src => src.ZipCodes)
        .Ignore(dest => dest.AffiliateId)
        .Ignore(dest => dest.Affiliate);


TypeAdapterConfig<ZipCodeDTO, ServiceAreaToZipCode>
    .NewConfig()
    .Map(dest => dest.ZipCode.Zip,
        src => src.Zip);
```

and [here's the rest of it](https://github.com/aspnet/EntityFrameworkCore/issues/10165#issuecomment-339722165)
 if you want me to paste the code here  as well i can. i don't know what they mean by examine the entity graph to find the difference. I cannot use the mapster debugger in core.

**Comment by chaowlert** [comment]
Thx u for the issue. It is bug. 

In fact, Mapster doesn't allow `Map(dest => dest.ZipCode.Zip`. What Maspter expects is just first level property in destination (ex `Map(dest => dest.Zip`). But because there is no error throw, so after mapping ZipCode will always be null.

In short run, I will throw exception when we pass nested property to Map function.
In long run, I will try to find way to support nested properties.

For now, as workaround, pls use following config

            TypeAdapterConfig<ZipCodeDTO, ServiceAreaToZipCode>
                .NewConfig()
                .Map(dest => dest.ZipCode,
                    src => new { src.Zip});

**Comment by chaowlert** [comment]
4.0 now support multi-level properties
