### ISSUE TITLE
Does anyone have an example on how to map a simple string into a complex type?

### ISSUE THREAD

**Issue by shanerogers** [MapsterMapper/Mapster#161]

**Comment by shanerogers** [comment]
I am trying to map a string to a complex type. A string that represents an account number. The complex type will have a a formatted acc no as provide below.

    "account": {
                "id": null,
                "accountNumberFormatted": null
            },

the boundry will eventually become json as above.

**Comment by chaowlert** [comment]
If your source/target type can be `JObject` instead of `string`,  you can use [Json plugin](https://github.com/MapsterMapper/Mapster/wiki/Json.net).

Or if you have specific destination type, then you can use [MapWith](https://github.com/MapsterMapper/Mapster/wiki/Custom-conversion-logic#custom-type-conversion)
```
TypeAdapterConfig<string, ComplexType>.NewConfig()
            .MapWith(str => JsonConvert.DeserializeObject<ComplexType>(str));
```

But if you would like to map string from/to generic complex type, you might need to create custom adapter. Pls see [JsonAdapter](https://github.com/MapsterMapper/Mapster.JsonNet/blob/master/Mapster.JsonNet/Mapster.JsonNet/JsonAdapter.cs) as an example.
