### ISSUE TITLE
Target class needs a parameterless constructor

### ISSUE THREAD

**Issue by smandli** [MapsterMapper/Mapster#166]
The library seems to be mapping all the objects values again )in this example of the object ThingDateConstraint), even though the object is being already constructed.
This means in this example that ThingDateConstraint needs to have a parameterless constructor, even though I've already built it.

`TypeAdapterConfig<UpdateThingRequest, Thing>.NewConfig()
  .Map(dest => dest.DateConstraint, src => new ThingDateConstraint(src.ValidFrom, src.ValidTo))`

I wonder if there is a different way to define a mapping which doesn't get mapped again under the hood, which enforces type compliance (both expressions have the same type)

**Comment by chaowlert** [comment]
I'm not entirely understand the case, my understanding is you might get error notify that Mapster cannot create `ThingDateConstraint` object (because default constructor not found).

By design, Mapster will try to deep clone object. Even you provide how to build `ThingDateConstraint` object, Mapster will again try to clone object you provided.

To turn off deep clone, you might need to config

```
TypeAdapterConfig<UpdateThingRequest, Thing>.NewConfig()
    .Map(dest => dest.DateConstraint, src => new ThingDateConstraint(src.ValidFrom, src.ValidTo))
    .ShallowCopyForSameType(true)
```

Anyway, I will look into how to make mapping better, in your case, `ThingDateConstraint` seemed doesn't need to clone again.

**Comment by smandli** [comment]
What's the reason behind ShallowCopyForSameType's default value being false?

Is that to avoid copying by reference?

**Comment by chaowlert** [comment]
Good question, main reason could be consistency. Since Mapster maps A to B will always create new B object. Therefore mapping A to A, should also creating new object.

Pls suggest, if you have different opinion.
