### ISSUE TITLE
Adapt is no longer working for existing List in 6.0+

### ISSUE THREAD

**Issue by ImGonaRot** [MapsterMapper/Mapster#271]
I recently updated from version from 4.1.0 to 6.5.0 and ran into the following problem.
My current code has been in production for about a year.

In Mapster 5.3.2 and below the following code works BUT in Mapster 6.0+ it does not work.
I have tried every version between 4.1.0 to 6.5.0 and they all work except the 6.0 versions.

```c#
List<Thing> things = GetThings();

List<Thing> moreThings = new List<Thing>();
things.Adapt(moreThings);

int countThings = moreThings.Count();
// At this point in 5.3.2 and below the countThings > 0
// BUT in 6.0+ the countThings == 0

```

As a side note the following does work in version 6.0+ but I would need to re-write a lot of my code to adjust to this pattern.
```c#
List<Thing> things = GetThings();

List<Thing> moreThings = things.Adapt<List<Thing>>();

int countThings = moreThings.Count();
// The count > 0 is true
```

**Comment by chaowlert** [comment]
I introduced map to existing list in v4, and remove in v6 because 
- it introduced some issues (#209, #247)
- EF doesn't require us to maintain object reference to list
- collection has many flavor (array, ReadOnlyList, IEnumerable), only List that can map to existing object.

Sorry for the change, seemed like you can find workaround solution.
I will add this breaking change in release note for v6.
