### ISSUE TITLE
BeforeMapping() error

### ISSUE THREAD

**Issue by omarattia3143** [MapsterMapper/Mapster#299]
Hello,

i am trying use BeforeMapping() to convert from base64 string to byte before mapping between dto and poco
for exmple:
```
            var poco = dto.Adapt<poco>(MapConfig.DtoToPoco());
```
and the TypeAdapterConfig is:
```
public static TypeAdapterConfig DtoToPoco()
        {
            var config = new TypeAdapterConfig();
            config.ForType<CustomerCarDto, CustomerCar>()
                .BeforeMapping((src,dest) => dest.Base64ToBinary(src.ImageUri));   //  ==>  Invalid cast from 'System.String' to 'System.Byte[]'.

            return config;
        }
```
and the conversion as simple as:
```
  public void Base64ToBinary(string img64)
        {
           ImageUri = Convert.FromBase64String(img64);
        }
```
so i get  Invalid cast from 'System.String' to 'System.Byte[]'. error though it's working fine with manual mapping so could you guide me what's wrong here ?

thank you

**Comment by chaowlert** [comment]
I think you need to ignore ImageUri first.

`config.ForType<CustomerCarDto, CustomerCar>().Ignore(dest => dest.ImageUri)`

Or you can just using `Map` rather than `BeforeMapping`.

`config.ForType<CustomerCarDto, CustomerCar>().Map(dest => dest.ImageUri, src => Convert.FromBase64String(src.ImageUri))`
