### ISSUE TITLE
Different Exception mapped when mapping an Exception object to a Property of type Exception on a Dto

### ISSUE THREAD

**Issue by stuart-hatfield-f4** [MapsterMapper/Mapster#322]
I am attempting to map an instance of an Exception to a similar typed Property on a Data Model.    The Mapping merges another Dto with values passed in as Parameters including the System.Exception into the target Model.

In older versions of Mapster (<=v5.3.2) this code worked fine and the Exception was logged as thrown.   Unfortunately since   version (>=v6.0.0) an Exception containing the message "Exception of type 'System.Exception' was thrown" is mapped to the Dto Property instead.   

If I track this to the point of the actual mapping in the .Map configuration the correct Exception can be seen so it is at the final step of the mapping into the dest.Exception that the Exception is replaced by another value.

Mapping configuration:

               config.NewConfig<RequestDetailsDto, RequestDetailsModel>()
               ..
                .Map(dest => dest.Exception, src => MapContext.Current.Parameters["Exception"])

Running of AdaptToType:

                  var requestDetails = requestDetailsDto
                  .BuildAdapter()
                  .AddParameters("Exception", requestDetailsDto.Exception)
                  .AdaptToType<RequestDetailsModel>();

Target Model:

    public class RequestDetailsModel
    {
        ...
        public Exception Exception { get; set; }
    }

This behaviour post version 6.0.0 is masking the correct Exception information in our logs with the "Exception of type 'System.Exception' was thrown" message instead.

Note - We looked at directly mapping the object .Map(dest => dest.Exception, src => src.Exception) instead of passing in the parameter and we get the same problem as above even in versions prior to 6.0.0, so the above approach of using the Parameter may have been implemented originally to get around this issue.

**Comment by chaowlert** [comment]
Sorry for late reply. Mapster uses heuristic approach to identify POCO. Mapster v5 identify Exception as an unidentified object. So it copy reference. In later version, Mapster identify Exception as POCO (as it's similar to record type), therefore, Mapster creates new Exception object rather than using the same reference.

I might not fix this. To solve this problem, I can think of 2 ways.

1. use [`ShallowCopyForSameType`](https://github.com/MapsterMapper/Mapster/wiki/Shallow-merge#deep-copy-vs-shallow-copy)
2. use `config.NewConfig<Exception, Exception>().MapWith(ex => ex)`
