### ISSUE TITLE
Mapping IDatareader

### ISSUE THREAD

**Issue by BlueMercs** [MapsterMapper/Mapster#61]
Hi, is it possible to map result from database from IDataReader to a poco? I have tried but the properties are not set with values. I am busy replacing Automapper with Mapster and really need to get this working. Thanks.

**Comment by chaowlert** [comment]
It doesn't support yet. But this could be done by overriding `BaseAdapter` and implementing logic to map between `IDataReader` to list of poco.

After finish, you can add new adapter by `TypeAdapterConfig.Default.Rules.Add(adapter.CreateRule())`.

If you have questions about implementing this feature, please feel free to ask. I will help as much as I can to support contribution.

**Comment by BlueMercs** [comment]
I really do not have the time to implement this, can you by any chance assist by implementing this feature?

**Comment by chaowlert** [comment]
I will keep this ticket open, in case someone else interested in this feature and would like to implement this.

**Comment by jbogard** [comment]
FYI I've moved this to a different repo in AutoMapper because it's all IL magic and I have no idea how it works. I'd at least recommend keeping it a separate repo - you're forced to reference System.Data and that makes it especially annoying for cross-platform work.

And unlike the LINQ mapping or Queryable mapping or ExpandoObject mapping or Dictionary mapping, IDataReader is just different, you're dealing with data provider junk. It's not fun.

**Comment by chaowlert** [comment]
I guess no one use `IDataReader` any more.
