### ISSUE TITLE
Removal of .Net 4.7+ and .Net Standard 2.0 support

### ISSUE THREAD

**Issue by madhon** [MapsterMapper/Mapster#636]
Is there a reason why .net 4.7+ and .Net standard 2.0 support has been removed from 7.4.0 when they are still supported by Microsoft  and not EOL as appears to be claimed ?

**Comment by andrerav** [comment]
I'm not sure why you're saying that anyone is "claiming" that .NET 4.7+ nor .NET Standard 2.0 is EOL. I think you are confusing this with the fact that was netcoreapp3.1, netcoreapp2.0, net45 and net40 were removed in https://github.com/MapsterMapper/Mapster/commit/00aab6801dd80fc30cbbb924650601046fa20b7c. These versions are in fact EOL. 

To bring back netstandard2.0 support, which I think is what you want, there are a number of code changes required since Mapster now relies on functionality that is not available on .netstandard2.0, especially related to reflection.
